media: img
content:
  - name: pages
    label: Pages
    type: collection
    path: _posts
    fields:
      - name: title
        type: string
      - name: tags
        type: string
        list: true
      - name: body
        type: rich-text